// Glidewell documentary timeline — data extracted from index.html (2026-07-29).
// Loaded before the main script; the variables stay global exactly as before.

const CAST_OUTREACH=[
  {k:"park", date:"2026-07-31", nm:"Neil Park", staff:true, who:{en:"Glidewell · VP Clinical Affairs",ru:"Glidewell · VP Clinical Affairs"}, loc:"Irvine", status:"confirmed", ball:"them", note:{en:"His reply (Jul 24, 2026):\n\n“That sounds great. I will look forward to meeting you on Friday, and then we can schedule the sit down discussion for another time, perhaps the next week.”\n\n— Neil Park",ru:"Его ответ (24 июля 2026):\n\n«That sounds great. I will look forward to meeting you on Friday, and then we can schedule the sit down discussion for another time, perhaps the next week.»\n\n— Neil Park"},
   shoot:{en:"Confirmed — replied yes. Fri Jul 31 on campus: we meet + grab reportage (his walk-out, the talk). The sit-down interview moves to the following week (early Aug) — day TBC.",ru:"Подтвердил — ответил «да». Пт 31 июля на кампусе: знакомимся + берём репортаж (выход, доклад). Само интервью — на следующую неделю (начало августа) — день уточняется."}},
  {k:"patel", date:"2026-08-06", nm:"Paresh Patel", staff:false, who:{en:"External · implants / access",ru:"Внешний · импланты / доступность"}, loc:"Raleigh area, NC", status:"confirmed", ball:"them",
   shoot:{en:"CONFIRMED by Patel ✓ — Full-Arch Symposium (Irvine). Interview Thu Aug 6, 10:15–11:45 a.m. in Studio 130 (right after his 9:15–9:45 “Guided by Design” talk); ~90 min + b-roll. Fri Aug 7 backup ~12–1:30 between his talks. RALEIGH IS BACK ON: b-roll at his clinic Sat Sep 19 afternoon, same trip as Kosinski's morning interview — we told him on Jul 27 we were setting Raleigh aside, so we have to re-open it. Raise it face-to-face on Aug 6, don't do it by email.",ru:"ПОДТВЕРДИЛ ✓ — Симпозиум Full-Arch (Ирвайн). Интервью чт 6 авг, 10:15–11:45 в Studio 130 (сразу после доклада 9:15–9:45 «Guided by Design»); ~90 мин + b-roll. Пт 7 авг резерв ~12–13:30 между докладами. RALEIGH ВЕРНУЛСЯ: b-roll в его клинике сб 19 сен во второй половине дня, тем же заездом, что и утреннее интервью с Косински — 27 июля мы написали ему, что Raleigh откладываем, теперь надо переоткрыть. Поднять лично 6 авг, не письмом."}},
  {k:"resnik", date:"2026-08-06", nm:"Randy Resnik", staff:false, who:{en:"External · implant education",ru:"Внешний · имплант-образование"}, loc:"Pittsburgh, PA", status:"confirmed",
   shoot:{en:"At the Full-Arch Symposium (Irvine). Interview Thu Aug 6, 12:00–1:30 p.m. (right after Patel wraps at 11:45); ~90 min + b-roll. Evening 5:00 slot dropped — Mesa Manor dinner. Morning is out — we're filming a scene both Patel & Resnik attend. Fri Aug 7 midday backup. Also in Irvine in November if needed.",ru:"На симпозиуме Full-Arch (Ирвайн). Интервью чт 6 авг, 12:00–13:30 (сразу после Patel в 11:45); ~90 мин + b-roll. Вечерний слот 17:00 снят — ужин в Mesa Manor. Утро занято — снимаем сцену, где будут и Patel, и Resnik. Пт 7 авг полдень — резерв. Также в Ирвайне в ноябре при необходимости."}},
  {k:"kosinski", date:"2026-09-19", nm:"Tim Kosinski", staff:false, who:{en:"External · implants",ru:"Внешний · импланты"}, loc:"Bingham Farms, MI", status:"confirmed", note:{en:"Jessica (his assistant), Jul 24, 2026:\n\n“We will be in Irvine for Dr. Kosinski's 2-day course on October 30-31 and for the Implant Symposium on November 6-7. He will be available on Thursday, October 29 or Thursday, November 5 to record — we usually land around 11am. Please let me know which date will work best.”\n\nEldon: also in Raleigh, NC in late August and again mid-September — if either earlier date is feasible, the crew might gameplan around those.",ru:"Джессика (ассистент), 24 июля 2026:\n\n“We will be in Irvine for Dr. Kosinski's 2-day course on October 30-31 and for the Implant Symposium on November 6-7. He will be available on Thursday, October 29 or Thursday, November 5 to record — we usually land around 11am.”\n\nЭльдон: также в Raleigh, NC в кон. августа и сер. сентября — если раньше удобнее, команда подстроится."},
   shoot:{en:"PLAN: Raleigh, Sat Sep 19, morning — at his course. Ivan flies out and runs the shoot on location; Eldar directs and conducts the interview over a video link (Kosinski to be told upfront). Same trip, same day: Patel b-roll at his clinic in the afternoon. Aug 28-29 Raleigh dropped — collides with Farran (locked Aug 28 on campus). Thu Oct 29 in Irvine stays as backup. Awaiting Jessica via Eldon.",ru:"ПЛАН: Raleigh, сб 19 сен, утро — вокруг его курса. Иван летит и ведёт съёмку на месте; Элдар режиссирует и берёт интервью по видеосвязи (Косински предупредить заранее). Тем же заездом, в тот же день: b-roll с Пателем в его клинике во второй половине дня. Raleigh 28-29 авг снят — конфликтует с Фарраном (зафиксирован 28 авг на кампусе). Чт 29 окт в Ирвайне остаётся резервом. Ждём Джессику через Эльдона."}},
  {k:"farran", date:"2026-08-28", nm:"Howard Farran", staff:false, note:{en:"His reply (Jul 24, 2026):\n\n“You are much busier than I am, so rather than working around my schedule, I’d rather work around yours. Just tell me the best date and time for me to fly out to Glidewell, and I’ll be there. Whatever works best for you and your team works for me.\n\nI’m genuinely honored to be included in this project. Jim’s story deserves to be told, and I can’t think of anyone more deserving. He changed dentistry by making high quality care more affordable for millions of patients, and I believe that legacy will only become more appreciated with time.\n\nI’m looking forward to meeting you and helping in any way I can. Just let me know where you need me, when you need me there, and what you’d like me to do.\n\nWarm regards,\nHoward”",ru:"Его ответ (24 июля 2026):\n\n“You are much busier than I am, so rather than working around my schedule, I’d rather work around yours. Just tell me the best date and time for me to fly out to Glidewell, and I’ll be there. Whatever works best for you and your team works for me.\n\nI’m genuinely honored to be included in this project. Jim’s story deserves to be told, and I can’t think of anyone more deserving. He changed dentistry by making high quality care more affordable for millions of patients, and I believe that legacy will only become more appreciated with time.\n\nI’m looking forward to meeting you and helping in any way I can. Just let me know where you need me, when you need me there, and what you’d like me to do.\n\nWarm regards,\nHoward”"}, who:{en:"External · Dentaltown",ru:"Внешний · Dentaltown"}, loc:"Phoenix, AZ", status:"confirmed",
   shoot:{en:"LOCKED ✓ — interview Fri Aug 28, 10:00 a.m.–12:00 p.m. on campus, at Summer IOX (The Digital Dentistry Experience, Aug 27-28); b-roll around the event. Replied via Eldon's thread: “I can't wait!”",ru:"ЗАФИКСИРОВАНО ✓ — интервью пт 28 авг, 10:00–12:00 на кампусе, в рамках Summer IOX (27-28 авг); b-roll вокруг события. Ответил в ветке Eldon: «I can't wait!»"}},
  {k:"ameduri", date:null, nm:"Anna Ameduri", staff:true, who:{en:"Glidewell · VP Global Logistics",ru:"Glidewell · VP глобальной логистики"}, loc:"Irvine", status:"sent", note:{en:"Invited by Eldon (internal email, Jul 24, 2026): ~90-min interview + footage in the natural work habitat. Awaiting scheduling.",ru:"Приглашён(а) Эльдоном (внутреннее письмо, 24 июля 2026): ~90-мин интервью + съёмка в рабочей среде. Ждём согласования дат."},
   shoot:{en:"Studio 130 on one of our studio days — ~45-60 min interview + b-roll.",ru:"Studio 130 в один из студийных дней — ~45-60 мин интервью + b-roll."}},
  {k:"labao", date:null, nm:"Edsel Labao", staff:true, who:{en:"Glidewell · VP IT",ru:"Glidewell · VP по ИТ"}, loc:"Orange County, CA", status:"sent", note:{en:"Invited by Eldon (internal email, Jul 24, 2026): ~90-min interview + footage in the natural work habitat. Awaiting scheduling.",ru:"Приглашён(а) Эльдоном (внутреннее письмо, 24 июля 2026): ~90-мин интервью + съёмка в рабочей среде. Ждём согласования дат."},
   shoot:{en:"Studio 130 on a studio day — ~45-60 min + b-roll; bring old photos / artifacts.",ru:"Studio 130 в студийный день — ~45-60 мин + b-roll; принести старые фото / артефакты."}},
  {k:"rella", date:"2026-10-06", nm:"Rella Christensen", staff:false, who:{en:"External · TRAC / CR Foundation — the BruxZir origin",ru:"Внешний · TRAC / CR Foundation — исток BruxZir"}, loc:"Provo, UT", status:"confirmed", note:{en:"Rella Christensen, PhD (Jul 25, 2026):\n\n“I would love to participate in your proposed documentary. Indeed there is a fascinating story to tell. My most exciting story to tell is about the rise of digital imaging and milling which we participated in from the beginning with the responsibility for objective controlled clinical practice-based testing of thousands of restorations since we initiated the work with CEREC technology, zirconia, and BruxZir. My team and I will be returning to our lab this coming Monday, July 27 from a Summer Break.”",ru:"Rella Christensen, PhD (25 июля 2026):\n\n“I would love to participate in your proposed documentary...” (полный текст EN). Команда возвращается в лабораторию в понедельник 27 июля."},
   shoot:{en:"Provo, UT — LOCK the week of Oct 5 (she offered Oct 5 or Oct 12; Oct 12 collides with the Oct 15-16 symposium/DOTR). Arrive Sun Oct 4 to scout so her team preps the areas; shoot Oct 6-7; back for the Oct 9-10 symposium. ~90-min interview + 1-2h b-roll. Biggest ‘get’ — she has enough zirconia-development material for a whole standalone history. Try to grab Gordon on the same trip.",ru:"Прово, Юта — ФИКСИРУЕМ неделю 5 окт (предложила 5 или 12 окт; 12-е конфликтует с симпозиумом/DOTR 15-16 окт). Приезд вс 4 окт на разведку, чтобы команда подготовила зоны; съёмка 6-7 окт; назад к симпозиуму 9-10 окт. ~90 мин интервью + 1-2ч b-roll. Крупнейший ‘get’ — материала по циркониевой истории хватит на отдельный фильм. Заодно попробовать Гордона."}},
  {k:"christensen", date:null, nm:"Gordon Christensen", staff:false, who:{en:"External · Clinicians Report — 50-yr independent authority",ru:"Внешний · Clinicians Report — 50-летний независимый авторитет"}, loc:"Provo, UT", status:"paused", shoot:{en:"Target to capture in Provo on the same trip as Rella. Not contacted directly yet.",ru:"Цель — снять в Прово тем же выездом, что и Реллу. Напрямую пока не связывались."}},
  {k:"brenneise", date:null, nm:"Robert Brenneise", staff:true, who:{en:"Glidewell · Chief Growth Officer",ru:"Glidewell · Chief Growth Officer"}, loc:"Irvine", status:"confirmed", ball:"them", note:{en:"His reply (Jul 25, 2026): “Sounds fun and thanks for the oppt!”",ru:"Его ответ (25 июля 2026): “Sounds fun and thanks for the oppt!”"}, shoot:{en:"Confirmed. Scheduling email sent Jul 27 (proposed Wed Aug 5, Studio 130, ~90 min) — awaiting his preferred day.",ru:"Подтвердил. Письмо с датами отправлено 27 июля (предложили ср 5 авг, Studio 130, ~90 мин) — ждём его удобный день."}},
  {k:"ceranic", date:null, nm:"Dzevad Ceranic", staff:true, who:{en:"Glidewell · Lab Operations",ru:"Glidewell · производство (Lab Ops)"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll.",ru:"Внутренний — приглашён Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll."}},
  {k:"fejzagic", date:null, nm:"Leila Fejzagic", staff:true, who:{en:"Glidewell · HR",ru:"Glidewell · HR"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll.",ru:"Внутренний — приглашена Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll."}},
  {k:"withrow", date:null, nm:"Darryl Withrow", staff:true, who:{en:"Glidewell · VP Operations",ru:"Glidewell · VP по операциям"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll. Role confirmed from Jim\u2019s book: VP of Operations.",ru:"Внутренний — приглашён Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll. Роль подтверждена по книге Джима: VP по операциям."}},
  {k:"feuerstein", date:null, nm:"Paul Feuerstein", staff:false, who:{en:"External · dental-tech (Dentistry Today)",ru:"Внешний · дент-технологии (Dentistry Today)"}, loc:"Billerica, MA", status:"paused",
   shoot:{en:"Proposed at a planning meeting — Eldon hasn't invited him. Decide whether to pursue and who does the first outreach.",ru:"Предложен на планёрке — Эльдон не писал. Решить: пускаем ли и кто пишет первым."}}
];
