// Glidewell documentary timeline — data extracted from index.html (2026-07-29).
// Loaded before the main script; the variables stay global exactly as before.

const CAST_OUTREACH=[
  {k:"park", date:"2026-07-31", nm:"Neil Park", staff:true, who:{en:"Glidewell · VP Clinical Affairs",ru:"Glidewell · VP Clinical Affairs"}, loc:"Irvine", status:"confirmed", ball:"them", note:{en:"His reply (Jul 24, 2026):\n\n“That sounds great. I will look forward to meeting you on Friday, and then we can schedule the sit down discussion for another time, perhaps the next week.”\n\n— Neil Park",ru:"Его ответ (24 июля 2026):\n\n«That sounds great. I will look forward to meeting you on Friday, and then we can schedule the sit down discussion for another time, perhaps the next week.»\n\n— Neil Park"},
   shoot:{en:"Confirmed — replied yes. Fri Jul 31 on campus: we meet + grab reportage (his walk-out, the talk). The sit-down interview moves to the following week (early Aug) — day TBC.",ru:"Подтвердил — ответил «да». Пт 31 июля на кампусе: знакомимся + берём репортаж (выход, доклад). Само интервью — на следующую неделю (начало августа) — день уточняется."}},
  {k:"patel", date:"2026-08-06", nm:"Paresh Patel", staff:false, who:{en:"External · implants / access",ru:"Внешний · импланты / доступность"}, loc:"Raleigh area, NC", status:"confirmed", ball:"them",
   shoot:{en:"CONFIRMED by Patel ✓ — Full-Arch Symposium (Irvine). Interview Thu Aug 6, 10:15–11:45 a.m. in Studio 130 (right after his 9:15–9:45 “Guided by Design” talk); ~90 min + b-roll. Fri Aug 7 backup ~12–1:30 between his talks. RALEIGH ON HOLD AGAIN: the Sep 19 pairing died with Kosinski's flight (Jessica, Aug 3). His clinic b-roll now has to stand on its own and needs a working weekday, not a weekend. Decide separately — don't raise a date with him until we have one.",ru:"ПОДТВЕРДИЛ ✓ — Симпозиум Full-Arch (Ирвайн). Интервью чт 6 авг, 10:15–11:45 в Studio 130 (сразу после доклада 9:15–9:45 «Guided by Design»); ~90 мин + b-roll. Пт 7 авг резерв ~12–13:30 между докладами. RALEIGH СНОВА НА ПАУЗЕ: связка 19 сен умерла вместе с рейсом Косински (Джессика, 3 авг). B-roll в его клинике теперь должен стоять сам по себе, и ему нужен рабочий будний день, а не выходной. Решать отдельно — не называть ему дату, пока её нет."}},
  {k:"resnik", date:"2026-08-06", nm:"Randy Resnik", staff:false, who:{en:"External · implant education",ru:"Внешний · имплант-образование"}, loc:"Pittsburgh, PA", status:"confirmed",
   shoot:{en:"At the Full-Arch Symposium (Irvine). Interview Thu Aug 6, 12:00–1:30 p.m. (right after Patel wraps at 11:45); ~90 min + b-roll. Evening 5:00 slot dropped — Mesa Manor dinner. Morning is out — we're filming a scene both Patel & Resnik attend. Fri Aug 7 midday backup. Also in Irvine in November if needed.",ru:"На симпозиуме Full-Arch (Ирвайн). Интервью чт 6 авг, 12:00–13:30 (сразу после Patel в 11:45); ~90 мин + b-roll. Вечерний слот 17:00 снят — ужин в Mesa Manor. Утро занято — снимаем сцену, где будут и Patel, и Resnik. Пт 7 авг полдень — резерв. Также в Ирвайне в ноябре при необходимости."}},
  {k:"kosinski", date:"2026-11-05", nm:"Tim Kosinski", staff:false, who:{en:"External · implants",ru:"Внешний · импланты"}, loc:"Bingham Farms, MI", status:"confirmed", note:{en:"Jessica (his assistant), Jul 24, 2026:\n\n“We will be in Irvine for Dr. Kosinski's 2-day course on October 30-31 and for the Implant Symposium on November 6-7. He will be available on Thursday, October 29 or Thursday, November 5 to record — we usually land around 11am. Please let me know which date will work best.”\n\nEldon: also in Raleigh, NC in late August and again mid-September — if either earlier date is feasible, the crew might gameplan around those.",ru:"Джессика (ассистент), 24 июля 2026:\n\n“We will be in Irvine for Dr. Kosinski's 2-day course on October 30-31 and for the Implant Symposium on November 6-7. He will be available on Thursday, October 29 or Thursday, November 5 to record — we usually land around 11am.”\n\nЭльдон: также в Raleigh, NC в кон. августа и сер. сентября — если раньше удобнее, команда подстроится."},
   shoot:{en:"SEP 19 IS DEAD — Jessica (Aug 3): his RDU→DTW return flight that Saturday gets him home too late, and the time is fixed. Her words: “waiting until October is the best option.” Two live options: (1) Sun Aug 30, morning, Raleigh — he'd stay an extra night, offered only “if it is imperative to record sooner”; (2) Irvine in the autumn. WORKING PLAN: Thu Nov 5, Irvine, in person — he's there for the Implant Symposium Nov 6-7 and Jessica offered that date herself back in July (they land ~11am). NOTE: Thu Oct 29, her other original offer, is no longer possible — Provo moved onto Oct 28-29. Awaiting our answer to Jessica.",ru:"19 СЕН ОТПАЛ — Джессика (3 авг): обратный рейс RDU→DTW в ту субботу привозит его домой слишком поздно, время рейса не двигается. Её слова: «waiting until October is the best option». Два живых варианта: (1) вс 30 авг, утро, Raleigh — он остаётся на лишнюю ночь, предложено только «если снять раньше критично»; (2) Ирвайн осенью. РАБОЧИЙ ПЛАН: чт 5 ноя, Ирвайн, лично — он приезжает на Implant Symposium 6-7 ноя, и Джессика сама называла эту дату ещё в июле (прилетают ~11:00). ВНИМАНИЕ: чт 29 окт, её второе исходное предложение, больше невозможно — на 28-29 окт встало Прово. Ждут нашего ответа."}},
  {k:"farran", date:"2026-08-28", nm:"Howard Farran", staff:false, note:{en:"His reply (Jul 24, 2026):\n\n“You are much busier than I am, so rather than working around my schedule, I’d rather work around yours. Just tell me the best date and time for me to fly out to Glidewell, and I’ll be there. Whatever works best for you and your team works for me.\n\nI’m genuinely honored to be included in this project. Jim’s story deserves to be told, and I can’t think of anyone more deserving. He changed dentistry by making high quality care more affordable for millions of patients, and I believe that legacy will only become more appreciated with time.\n\nI’m looking forward to meeting you and helping in any way I can. Just let me know where you need me, when you need me there, and what you’d like me to do.\n\nWarm regards,\nHoward”",ru:"Его ответ (24 июля 2026):\n\n“You are much busier than I am, so rather than working around my schedule, I’d rather work around yours. Just tell me the best date and time for me to fly out to Glidewell, and I’ll be there. Whatever works best for you and your team works for me.\n\nI’m genuinely honored to be included in this project. Jim’s story deserves to be told, and I can’t think of anyone more deserving. He changed dentistry by making high quality care more affordable for millions of patients, and I believe that legacy will only become more appreciated with time.\n\nI’m looking forward to meeting you and helping in any way I can. Just let me know where you need me, when you need me there, and what you’d like me to do.\n\nWarm regards,\nHoward”"}, who:{en:"External · Dentaltown",ru:"Внешний · Dentaltown"}, loc:"Phoenix, AZ", status:"confirmed",
   shoot:{en:"LOCKED ✓ — interview Fri Aug 28, 10:00 a.m.–12:00 p.m. on campus, at Summer IOX (The Digital Dentistry Experience, Aug 27-28); b-roll around the event. Replied via Eldon's thread: “I can't wait!”",ru:"ЗАФИКСИРОВАНО ✓ — интервью пт 28 авг, 10:00–12:00 на кампусе, в рамках Summer IOX (27-28 авг); b-roll вокруг события. Ответил в ветке Eldon: «I can't wait!»"}},
  {k:"ameduri", date:null, nm:"Anna Ameduri", staff:true, who:{en:"Glidewell · VP Global Logistics",ru:"Glidewell · VP глобальной логистики"}, loc:"Irvine", status:"sent", note:{en:"Invited by Eldon (internal email, Jul 24, 2026): ~90-min interview + footage in the natural work habitat. Awaiting scheduling.",ru:"Приглашён(а) Эльдоном (внутреннее письмо, 24 июля 2026): ~90-мин интервью + съёмка в рабочей среде. Ждём согласования дат."},
   shoot:{en:"Studio 130 on one of our studio days — ~45-60 min interview + b-roll.",ru:"Studio 130 в один из студийных дней — ~45-60 мин интервью + b-roll."}},
  {k:"labao", date:null, nm:"Edsel Labao", staff:true, who:{en:"Glidewell · VP IT",ru:"Glidewell · VP по ИТ"}, loc:"Orange County, CA", status:"sent", note:{en:"Invited by Eldon (internal email, Jul 24, 2026): ~90-min interview + footage in the natural work habitat. Awaiting scheduling.",ru:"Приглашён(а) Эльдоном (внутреннее письмо, 24 июля 2026): ~90-мин интервью + съёмка в рабочей среде. Ждём согласования дат."},
   shoot:{en:"Studio 130 on a studio day — ~45-60 min + b-roll; bring old photos / artifacts.",ru:"Studio 130 в студийный день — ~45-60 мин + b-roll; принести старые фото / артефакты."}},
  {k:"rella", date:"2026-10-28", nm:"Rella Christensen", staff:false, who:{en:"External · TRAC / CR Foundation — the BruxZir origin",ru:"Внешний · TRAC / CR Foundation — исток BruxZir"}, loc:"Provo, UT", status:"confirmed", note:{en:"Rella Christensen, PhD (Jul 25, 2026):\n\n“I would love to participate in your proposed documentary. Indeed there is a fascinating story to tell. My most exciting story to tell is about the rise of digital imaging and milling which we participated in from the beginning with the responsibility for objective controlled clinical practice-based testing of thousands of restorations since we initiated the work with CEREC technology, zirconia, and BruxZir. My team and I will be returning to our lab this coming Monday, July 27 from a Summer Break.”",ru:"Rella Christensen, PhD (25 июля 2026):\n\n“I would love to participate in your proposed documentary...” (полный текст EN). Команда возвращается в лабораторию в понедельник 27 июля."},
   shoot:{en:"MOVED to Wed Oct 28 + Thu Oct 29, Provo, UT — she set the dates herself (letter of Aug 3, after a Jul 31 call with Eldon). Reason: those are the days the people actually running the Clinical Studies Department are on site. Wed 28 — we tour the facility and pick the areas; Thu 29 — the shoot, interview with her possibly in her current lab. Five people on camera for the lab sequence: Derek Hein (CEO, Clinicians Report), Scott Malcom (administers Clinical Studies), plus Colette Hansen, David Gold, Drew Parker. Lab work to be filmed silent, or with Rella narrating the steps as they happen. Kaesy Barker is arranging the hotel they use for course attendees. Our setup: Eldar conducts the interview remotely, Ivan on location for the interview + reportage of the lab. OPEN: she never answered the Gordon question.",ru:"ПЕРЕНЕСЕНО на ср 28 + чт 29 окт, Прово, Юта — даты назначила она сама (письмо 3 авг, после звонка с Эльдоном 31 июля). Причина: именно в эти дни на месте люди, реально ведущие отдел клинических исследований. Ср 28 — обходим комплекс и выбираем зоны; чт 29 — съёмка, интервью с ней, возможно в её нынешней лаборатории. В лабораторной сцене пять человек: Derek Hein (CEO, Clinicians Report), Scott Malcom (руководит отделом клинических исследований), плюс Colette Hansen, David Gold, Drew Parker. Работу лаборатории снимаем без звука либо с её закадровым комментарием по ходу. Kaesy Barker занимается отелем, который они дают слушателям курсов. Наша схема: Элдар ведёт интервью удалённо, Иван на месте — интервью + репортаж по лаборатории. ОТКРЫТО: на вопрос про Гордона она не ответила."}},
  {k:"christensen", date:null, nm:"Gordon Christensen", staff:false, who:{en:"External · Clinicians Report — 50-yr independent authority",ru:"Внешний · Clinicians Report — 50-летний независимый авторитет"}, loc:"Provo, UT", status:"paused", shoot:{en:"Target to capture in Provo on the same trip as Rella. Not contacted directly yet.",ru:"Цель — снять в Прово тем же выездом, что и Реллу. Напрямую пока не связывались."}},
  {k:"brenneise", date:null, nm:"Robert Brenneise", staff:true, who:{en:"Glidewell · Chief Growth Officer",ru:"Glidewell · Chief Growth Officer"}, loc:"Irvine", status:"confirmed", ball:"them", note:{en:"His reply (Jul 25, 2026): “Sounds fun and thanks for the oppt!”",ru:"Его ответ (25 июля 2026): “Sounds fun and thanks for the oppt!”"}, shoot:{en:"Confirmed. Scheduling email sent Jul 27 (proposed Wed Aug 5, Studio 130, ~90 min) — awaiting his preferred day.",ru:"Подтвердил. Письмо с датами отправлено 27 июля (предложили ср 5 авг, Studio 130, ~90 мин) — ждём его удобный день."}},
  {k:"ceranic", date:null, nm:"Dzevad Ceranic", staff:true, who:{en:"Glidewell · Lab Operations",ru:"Glidewell · производство (Lab Ops)"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll.",ru:"Внутренний — приглашён Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll."}},
  {k:"fejzagic", date:null, nm:"Leila Fejzagic", staff:true, who:{en:"Glidewell · HR",ru:"Glidewell · HR"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll.",ru:"Внутренний — приглашена Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll."}},
  {k:"withrow", date:null, nm:"Darryl Withrow", staff:true, who:{en:"Glidewell · VP Operations",ru:"Glidewell · VP по операциям"}, loc:"Irvine", status:"sent", shoot:{en:"Internal — invited by Eldon (Jul 24). Awaiting reply. ~90-min interview + b-roll. Role confirmed from Jim\u2019s book: VP of Operations.",ru:"Внутренний — приглашён Эльдоном (24 июля). Ждём ответ. ~90 мин интервью + b-roll. Роль подтверждена по книге Джима: VP по операциям."}},
  {k:"feuerstein", date:null, nm:"Paul Feuerstein", staff:false, who:{en:"External · dental-tech (Dentistry Today)",ru:"Внешний · дент-технологии (Dentistry Today)"}, loc:"Billerica, MA", status:"paused",
   shoot:{en:"Proposed at a planning meeting — Eldon hasn't invited him. Decide whether to pursue and who does the first outreach.",ru:"Предложен на планёрке — Эльдон не писал. Решить: пускаем ли и кто пишет первым."}}
];
