/* generated by qa/plan_dump.mjs from expo.html?plan=1 — do not edit by hand */
window.PLAN = {
 "version": 2,
 "date": "2026-09-21",
 "assetV": "20260911-gmain",
 "cam": {
  "F": 900,
  "horizon": 430,
  "benchY": 700,
  "benchDepth": 340,
  "floor": 1080
 },
 "world": {
  "x0": -3450,
  "end": 41300,
  "showL": 36640,
  "showR": 41600,
  "factX": 30890
 },
 "eras": [
  {
   "n": 1,
   "x0": -3450,
   "x1": 9370,
   "z0": 550,
   "tz": 550,
   "wall": "wall1",
   "font": "Georgia, \"Iowan Old Style\", \"Palatino Linotype\", serif",
   "fontYear": null,
   "lamp": "bulb",
   "floorPlate": false,
   "plateBench": true
  },
  {
   "n": 2,
   "x0": 10470,
   "x1": 13620,
   "z0": 680,
   "tz": 680,
   "wall": "wall2",
   "font": "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
   "fontYear": null,
   "lamp": "tube",
   "floorPlate": false,
   "plateBench": false
  },
  {
   "n": 3,
   "x0": 14720,
   "x1": 23960,
   "z0": 850,
   "tz": 680,
   "wall": "wall3",
   "font": "Verdana, Tahoma, \"DejaVu Sans\", sans-serif",
   "fontYear": "\"Nineties Wide\",\"Arial Black\",Impact,sans-serif",
   "lamp": "tube",
   "floorPlate": false,
   "plateBench": false
  },
  {
   "n": 4,
   "x0": 25040,
   "x1": 44100,
   "z0": 1400,
   "tz": 680,
   "wall": "wall4",
   "font": "\"Avenir Next\", \"Helvetica Neue\", Helvetica, Arial, sans-serif",
   "fontYear": null,
   "lamp": "tube",
   "floorPlate": true,
   "plateBench": false
  }
 ],
 "recs": [
  {
   "name": "1979",
   "x0": 9370,
   "x1": 10470,
   "z": 610,
   "kind": "portal"
  },
  {
   "name": "1989",
   "x0": 13620,
   "x1": 14720,
   "z": 728,
   "kind": "portal"
  },
  {
   "name": "1993",
   "x0": 15445,
   "x1": 16395,
   "z": 728,
   "kind": "plinth"
  },
  {
   "name": "Digital Revolution",
   "x0": 23960,
   "x1": 25040,
   "z": 970,
   "kind": "portal"
  },
  {
   "name": "2017 glass hall",
   "x0": 35130,
   "x1": 38610,
   "z": 1000,
   "kind": "room"
  },
  {
   "name": "2018",
   "x0": 29270,
   "x1": 30170,
   "z": 1000,
   "kind": "bench"
  },
  {
   "name": "2022",
   "x0": 31960,
   "x1": 32760,
   "z": 1000,
   "kind": "plinth"
  },
  {
   "name": "2023",
   "x0": 33470,
   "x1": 34370,
   "z": 1000,
   "kind": "bench"
  }
 ],
 "hall": {
  "frameL": 35080,
  "frameR": 36580,
  "mid": 35830,
  "portalZ": 992,
  "roomZ": 1850,
  "pedZ": 420,
  "pedH": 340,
  "carpet": {
   "zFar": 900,
   "zNear": 300
  }
 },
 "plates": [
  {
   "x": 4310,
   "sw": 1874,
   "layers": [
    {
     "img": "plate_bay_front.png",
     "z": 0
    }
   ]
  }
 ],
 "cuts": [
  {
   "x": 1900,
   "w": 700
  },
  {
   "x": 2450,
   "w": 2320
  },
  {
   "x": 12150,
   "w": 1500
  },
  {
   "x": 24450,
   "w": 1500
  },
  {
   "x": 26900,
   "w": 2000
  },
  {
   "x": 27050,
   "w": 3600
  }
 ],
 "breaks": [
  {
   "x": 12270,
   "half": 65,
   "tag": null
  },
  {
   "x": 17620,
   "half": 65,
   "tag": null
  },
  {
   "x": 21420,
   "half": 65,
   "tag": null
  },
  {
   "x": 26800,
   "half": 65,
   "tag": null
  },
  {
   "x": 7050,
   "half": 820,
   "tag": "1973 stones"
  },
  {
   "x": 30890,
   "half": 560,
   "tag": null
  },
  {
   "x": 35830,
   "half": 581,
   "tag": null
  },
  {
   "x": 9920,
   "half": 780,
   "tag": null
  },
  {
   "x": 15590,
   "half": 870,
   "tag": null
  },
  {
   "x": 14170,
   "half": 330,
   "tag": null
  },
  {
   "x": 20482,
   "half": 330,
   "tag": null
  },
  {
   "x": 23220,
   "half": 330,
   "tag": null
  },
  {
   "x": 35830,
   "half": 330,
   "tag": null
  },
  {
   "x": 2545,
   "half": 486,
   "tag": null
  },
  {
   "x": 32285,
   "half": 325,
   "tag": null
  }
 ],
 "tables": [
  {
   "x0": -3450,
   "x1": 2058,
   "era": 1,
   "how": "sheet",
   "sheet": "bench_age01",
   "top": null,
   "face": null
  },
  {
   "x0": 3031,
   "x1": 6230,
   "era": 1,
   "how": "plate",
   "sheet": "plate_bay_front",
   "top": null,
   "face": null
  },
  {
   "x0": 7870,
   "x1": 9140,
   "era": 1,
   "how": "plate",
   "sheet": "plate_bay_front",
   "top": null,
   "face": null
  },
  {
   "x0": 10700,
   "x1": 12205,
   "era": 2,
   "how": "sheet",
   "sheet": "bench_1980",
   "top": null,
   "face": null
  },
  {
   "x0": 12335,
   "x1": 13730,
   "era": 2,
   "how": "sheet",
   "sheet": "bench_1980",
   "top": null,
   "face": null
  },
  {
   "x0": 16460,
   "x1": 17555,
   "era": 3,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "процедурная"
  },
  {
   "x0": 17685,
   "x1": 20152,
   "era": 3,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "процедурная"
  },
  {
   "x0": 20812,
   "x1": 21355,
   "era": 3,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "процедурная"
  },
  {
   "x0": 21485,
   "x1": 22890,
   "era": 3,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "процедурная"
  },
  {
   "x0": 23550,
   "x1": 24070,
   "era": 3,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "процедурная"
  },
  {
   "x0": 24930,
   "x1": 26735,
   "era": 4,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "фото front_e4.webp"
  },
  {
   "x0": 26865,
   "x1": 30330,
   "era": 4,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "фото front_e4.webp"
  },
  {
   "x0": 31450,
   "x1": 31960,
   "era": 4,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "фото front_e4.webp"
  },
  {
   "x0": 32610,
   "x1": 35248,
   "era": 4,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "фото front_e4.webp"
  },
  {
   "x0": 36411,
   "x1": 40000,
   "era": 4,
   "how": "proc",
   "sheet": null,
   "top": "процедурная",
   "face": "фото front_e4.webp"
  }
 ],
 "beats": [
  {
   "y": "1907",
   "t": "LOST-WAX CASTING",
   "x": 1050,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 1,
   "ped": null,
   "wall": [
    {
     "img": "cast",
     "dx": -430,
     "w": 360,
     "cy": 480.8776595744681,
     "cap": null,
     "pz": null
    },
    {
     "img": "furnace",
     "dx": 430,
     "w": 360,
     "cy": 480.8776595744681,
     "cap": null,
     "pz": null
    },
    {
     "img": "old1",
     "dx": -4328.839590443686,
     "w": 259.7952218430034,
     "cy": 525,
     "cap": "The tooth-drawer · 18th century",
     "pz": null
    },
    {
     "img": "old2",
     "dx": -3946.106926552112,
     "w": 290,
     "cy": 463.9306358381503,
     "cap": "Dentistry before the laboratory",
     "pz": null
    },
    {
     "img": "old3",
     "dx": -3546.962417881592,
     "w": 290,
     "cy": 521.1343930635838,
     "cap": "The barber-surgeon’s chair",
     "pz": null
    },
    {
     "img": "old4",
     "dx": -3147.817909211072,
     "w": 290,
     "cy": 491.7991329479769,
     "cap": "The old fear of the dentist",
     "pz": null
    }
   ],
   "onCounter": [
    {
     "name": "invest",
     "dx": -390,
     "lz": 12,
     "w": 280
    },
    {
     "name": "wax",
     "dx": 105,
     "lz": 12,
     "w": 280
    }
   ],
   "page": {
    "words": 272,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1970",
   "t": "FOUNDED",
   "x": 4310,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 1,
   "ped": null,
   "wall": [
    {
     "img": "jim1970",
     "dx": -820,
     "w": 620,
     "cy": 312.3165137614679,
     "cap": null,
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 566,
    "photos": 1,
    "voices": 1,
    "people": 1,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1970s",
   "t": "PFM ERA",
   "x": 5680,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 1,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 467,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1973",
   "t": "SECOND LAB",
   "x": 7050,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 1,
   "ped": null,
   "wall": [
    {
     "img": "rose",
     "dx": -1040,
     "w": 300,
     "cy": 501.9151376146789,
     "cap": null,
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 346,
    "photos": 3,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1976",
   "t": "DIRECT-MAIL",
   "x": 8420,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 1,
   "ped": null,
   "wall": [
    {
     "img": "jim76",
     "dx": -10,
     "w": 321.0204081632653,
     "cy": 525,
     "cap": null,
     "pz": null
    },
    {
     "img": "lab4int",
     "dx": 660,
     "w": 377.1428571428571,
     "cy": 525,
     "cap": null,
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 793,
    "photos": 1,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1979",
   "t": "NINE LABS",
   "x": 9920,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 1,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 362,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1980",
   "t": "STUDY PROGRAM",
   "x": 11257,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 2,
   "ped": null,
   "wall": [
    {
     "img": "joeha",
     "dx": -240,
     "w": 222.63698630136986,
     "cy": 525,
     "cap": null,
     "pz": null
    },
    {
     "img": "lab3ext",
     "dx": 847.0150660792951,
     "w": 380,
     "cy": 480.737885462555,
     "cap": null,
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 376,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1984",
   "t": "CONSOLIDATION",
   "x": 12045,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 2,
   "ped": null,
   "wall": [
    {
     "img": "lab3ben",
     "dx": -440,
     "w": 399.52,
     "cy": 525,
     "cap": null,
     "pz": null
    },
    {
     "img": "lab3rec",
     "dx": 548.6251982378872,
     "w": 380,
     "cy": 516.9383259911895,
     "cap": null,
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 370,
    "photos": 3,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1988",
   "t": "BIOTEMPS",
   "x": 12832,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 2,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 301,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1989",
   "t": "NATIONAL LEADER",
   "x": 14170,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 2,
   "ped": {
    "dx": 0,
    "obj": null,
    "spin": false,
    "points": false,
    "vitrine": false,
    "big": false,
    "z": -90,
    "gapHalf": 330
   },
   "wall": [],
   "onCounter": [
    {
     "name": "lab5move",
     "dx": -750,
     "lz": 12,
     "w": 250
    }
   ],
   "page": {
    "words": 374,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1993",
   "t": null,
   "x": 15920,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 512,
    "photos": 1,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1995",
   "t": "OPERATORY · PLAYSAFE",
   "x": 16832,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [
    {
     "name": "crt",
     "dx": -160,
     "lz": 75,
     "w": 290
    }
   ],
   "page": {
    "words": 277,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1996",
   "t": "SILENT NITE",
   "x": 17745,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 283,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1998",
   "t": "CHAIRSIDE PERSPECTIVES",
   "x": 18657,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [
    {
     "img": "chairv1",
     "dx": -340,
     "w": 285,
     "cy": 331.40337423312883,
     "cap": "Vol 1, Issue 1 · 2006",
     "pz": null
    },
    {
     "img": "chairv12",
     "dx": 55.22699386502791,
     "w": 285,
     "cy": 331.40337423312883,
     "cap": "Vol 12 · 2017",
     "pz": null
    },
    {
     "img": "chairv21",
     "dx": 450.4539877300558,
     "w": 285,
     "cy": 329.4363496932515,
     "cap": "Vol 21 · 2026",
     "pz": null
    }
   ],
   "onCounter": [],
   "page": {
    "words": 336,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "1999",
   "t": "IN-CERAM ZIRCONIA",
   "x": 19570,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 410,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2000",
   "t": "R&D IS BORN",
   "x": 20482,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 3,
   "ped": {
    "dx": 0,
    "obj": "puck",
    "spin": false,
    "points": false,
    "vitrine": false,
    "big": false,
    "z": -90,
    "gapHalf": 330
   },
   "wall": [
    {
     "img": "rella",
     "dx": 555,
     "w": 250,
     "cy": 353.5869565217391,
     "cap": "Dr. Rella Christensen",
     "pz": null
    }
   ],
   "onCounter": [
    {
     "name": "crt",
     "dx": 666.5,
     "lz": 130,
     "w": 320
    }
   ],
   "page": {
    "words": 657,
    "photos": 1,
    "voices": 0,
    "people": 1,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2001",
   "t": "WEB · CLINICAL VOICE",
   "x": 21395,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 302,
    "photos": 0,
    "voices": 0,
    "people": 1,
    "links": true,
    "inline": false
   }
  },
  {
   "y": "2000",
   "t": "PLASTIC INJECTION",
   "x": 21680,
   "sub": true,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 344,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2005",
   "t": "PRISMATIK",
   "x": 22307,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 3,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 350,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2007",
   "t": "FIRST DIGITAL CASE",
   "x": 23220,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 3,
   "ped": {
    "dx": 0,
    "obj": "dataTooth",
    "spin": false,
    "points": true,
    "vitrine": false,
    "big": false,
    "z": -90,
    "gapHalf": 330
   },
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 347,
    "photos": 0,
    "voices": 1,
    "people": 2,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2009",
   "t": "BRUXZIR",
   "x": 25600,
   "sub": false,
   "sign": null,
   "fly": true,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 550,
    "photos": 0,
    "voices": 0,
    "people": 2,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2009–13",
   "t": "SCREW-RETAINED",
   "x": 26424,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 391,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2010s",
   "t": "SCANNERS · SCALE",
   "x": 27248,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 306,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2015",
   "t": "HAHN TAPERED IMPLANT",
   "x": 28072,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 583,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2017",
   "t": "GLIDEWELL.IO",
   "x": 28896,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 351,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2018",
   "t": null,
   "x": 29720,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 379,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2019",
   "t": "BRUXZIR FACTORY",
   "x": 30890,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 441,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2019",
   "t": "GUIDING LEADERS",
   "x": 31510,
   "sub": true,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [
    {
     "name": "ellen",
     "dx": 55,
     "lz": 30,
     "w": 120
    },
    {
     "name": "nadia",
     "dx": 206,
     "lz": 30,
     "w": 120
    },
    {
     "name": "bianca",
     "dx": 354,
     "lz": 30,
     "w": 120
    }
   ],
   "page": {
    "words": 380,
    "photos": 0,
    "voices": 1,
    "people": 3,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2022",
   "t": "FASTSCAN.IO",
   "x": 32360,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 371,
    "photos": 0,
    "voices": 0,
    "people": 0,
    "links": false,
    "inline": false
   }
  },
  {
   "y": "2023",
   "t": "THE CROSSOVER",
   "x": 33920,
   "sub": false,
   "sign": null,
   "fly": false,
   "era": 4,
   "ped": null,
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 366,
    "photos": 0,
    "voices": 1,
    "people": 0,
    "links": false,
    "inline": true
   }
  },
  {
   "y": "2026",
   "t": null,
   "x": 39800,
   "sub": false,
   "sign": "TODAY",
   "fly": true,
   "era": 4,
   "ped": {
    "dx": -3970,
    "obj": "crown2",
    "spin": true,
    "points": false,
    "vitrine": false,
    "big": true,
    "z": 420,
    "gapHalf": 330
   },
   "wall": [],
   "onCounter": [],
   "page": {
    "words": 401,
    "photos": 0,
    "voices": 0,
    "people": 1,
    "links": false,
    "inline": false
   }
  }
 ],
 "lamps": [
  -650,
  1050,
  2333,
  3255,
  4310,
  5100,
  6022,
  7050,
  7866,
  8420,
  11257,
  12045,
  12832,
  15290,
  15920,
  17090,
  17990,
  18890,
  19790,
  20802,
  21590,
  22490,
  23540,
  25600,
  26610,
  27248,
  28896,
  29720,
  30890,
  31445,
  32360,
  33380,
  33920,
  35314,
  36281,
  37248,
  38215,
  39182,
  40149,
  41116,
  41370
 ],
 "lampZ": 240,
 "chandeliers": {
  "z": 520,
  "x": [
   37940,
   39680,
   41260
  ]
 },
 "figures": [
  {
   "x": 21220,
   "z": 560
  },
  {
   "x": 40680,
   "z": 470
  },
  {
   "x": 40580,
   "z": 390
  },
  {
   "x": 40740,
   "z": 300
  }
 ],
 "machines": [
  {
   "name": "near cell",
   "x": 30590,
   "z": 190
  },
  {
   "name": "far cell",
   "x": 31140,
   "z": 232
  }
 ],
 "exhibits": [
  {
   "kind": "plinth",
   "z": 120,
   "name": "1973 · две лаборатории на камнях",
   "x": 7050,
   "w": 760
  },
  {
   "kind": "plinth",
   "z": 120,
   "name": "1979 · восемь лабораторий на плинте",
   "x": 9920,
   "w": 1400
  },
  {
   "kind": "plinth",
   "z": 430,
   "name": "1979 · главное здание на блоке",
   "x": 9920,
   "w": 1040
  },
  {
   "kind": "model",
   "z": 240,
   "name": "1993 · макет здания",
   "x": 15920,
   "w": 330
  },
  {
   "kind": "machine",
   "z": 190,
   "name": "фрезерная ячейка, ближняя",
   "x": 30590,
   "w": 520
  },
  {
   "kind": "machine",
   "z": 232,
   "name": "фрезерная ячейка, дальняя",
   "x": 31140,
   "w": 520
  },
  {
   "kind": "projector",
   "z": 240,
   "name": "проектор 1993",
   "x": 16260,
   "w": 900
  }
 ],
 "projectors": [
  {
   "x": 16260,
   "pz": 728,
   "throwZ": 240,
   "src": "media/reel_1993.mp4"
  }
 ],
 "flybys": [
  {
   "y": "1998",
   "x": 18657,
   "dir": 1,
   "cy": 178,
   "z": 640,
   "code": "drawFlybys"
  },
  {
   "y": "2005",
   "x": 22307,
   "dir": -1,
   "cy": 292,
   "z": 640,
   "code": "drawFlybys"
  }
 ],
 "relays": [
  {
   "name": "1993 aeroplane",
   "from": "1989 pedestal centre",
   "to": "1993 centre",
   "code": "PLANE93"
  },
  {
   "name": "2007 data",
   "from": "2007 point cloud",
   "to": "Digital Revolution screen",
   "code": "drawDataRelay07"
  },
  {
   "name": "2018 data",
   "from": "2018 vitrine",
   "to": "2019 factory pendant",
   "code": "drawAIRelay"
  }
 ],
 "props": {
  "bench": 6,
  "sheets": 1,
  "fg": 0
 },
 "assets": {
  "photo": [
   "wall_e1_1907",
   "wall_e2",
   "wall_e1",
   "wall_e4",
   "bench_top_e1",
   "wall_e3",
   "bench_face_e1",
   "ph_furnace",
   "ph_articulator",
   "ph_jars",
   "ph_polisher",
   "ph_tray34",
   "ph_crate",
   "ph_cabinet",
   "ph_scanner",
   "ph_casebox",
   "ph_mill",
   "ph_scanbay",
   "ph_hall_wall",
   "ph_hall_floor",
   "ph_hall_plinth",
   "ph_album",
   "ph_pfm1",
   "ph_pfm2",
   "ph_pfm4",
   "ph_pfm5",
   "ph_pfm3",
   "ph_pfm6",
   "ph_pfmrow",
   "ph_plane",
   "ph_postbox",
   "ph_plastic",
   "ph_tv70",
   "ph_prj93",
   "ph_g8",
   "ph_labs73",
   "ph_car79",
   "ph_gmain",
   "front_e4",
   "bench_1980",
   "bench_age01"
  ],
  "sprites": [
   "wall_e1_1907",
   "wall_e2",
   "wall_e1",
   "wall_e4",
   "bench_top_e1",
   "wall_e3",
   "bench_face_e1",
   "ph_furnace",
   "ph_articulator",
   "ph_jars",
   "ph_polisher",
   "ph_tray34",
   "ph_crate",
   "ph_cabinet",
   "ph_scanner",
   "ph_casebox",
   "ph_mill",
   "ph_scanbay",
   "ph_hall_wall",
   "ph_hall_floor",
   "ph_hall_plinth",
   "ph_album",
   "ph_pfm1",
   "ph_pfm2",
   "ph_pfm4",
   "ph_pfm5",
   "ph_pfm3",
   "ph_pfm6",
   "ph_pfmrow",
   "ph_plane",
   "ph_postbox",
   "ph_plastic",
   "ph_tv70",
   "ph_prj93",
   "ph_g8",
   "ph_labs73",
   "ph_car79",
   "ph_gmain",
   "front_e4",
   "bench_1980",
   "bench_age01",
   "jar",
   "plaster",
   "toolbox",
   "mailtray",
   "box",
   "papers",
   "crtOff",
   "mill",
   "palmNear",
   "jaw1",
   "jaw2",
   "gradcap"
  ],
  "embedded": [
   "artic",
   "bianca",
   "bizcard",
   "bookfront",
   "bookspine",
   "cast",
   "chairv1",
   "chairv12",
   "chairv21",
   "christensen",
   "dietrim",
   "ditolla",
   "ellen",
   "fastmill",
   "father42",
   "furnace",
   "invest",
   "jim15",
   "jim18",
   "jim1970",
   "jim76",
   "jimnow",
   "joeha",
   "lab3ben",
   "lab3ext",
   "lab3rec",
   "lab4ext",
   "lab4int",
   "lab5move",
   "logo1970",
   "logo2026",
   "nadia",
   "old1",
   "old2",
   "old3",
   "old4",
   "patel",
   "porc",
   "qr",
   "rella",
   "rose",
   "todayai",
   "wax"
  ],
  "fonts": [
   "Courier Prime",
   "Courier Prime",
   "Courier Prime",
   "IBM Plex Sans",
   "IBM Plex Sans",
   "IBM Plex Sans",
   "Source Sans 3",
   "Source Sans 3",
   "Source Sans 3",
   "Inter",
   "Inter",
   "Inter",
   "Nineties Wide"
  ],
  "media": [
   "media/azernikov_01.mp4",
   "media/jim_glass.mp4",
   "media/park_08.mp4",
   "media/park_06.mp4",
   "media/park_07.mp4",
   "media/2007_patel.mp4",
   "media/resnik_01.mp4",
   "media/2010s_patel.mp4",
   "media/park_09.mp4",
   "media/park_01.mp4",
   "media/resnik_02.mp4"
  ]
 },
 "people": [
  "jim",
  "rella",
  "ditolla",
  "gordon",
  "ellen",
  "nadia",
  "bianca",
  "park",
  "patel",
  "resnik",
  "alas",
  "marie",
  "june",
  "jimlam",
  "julio",
  "joan",
  "labar",
  "sohn",
  "wali",
  "venard",
  "ceranic",
  "fejzagic",
  "withrow",
  "friebauer",
  "kois",
  "spear",
  "manalili",
  "kosinski",
  "chi",
  "leeson",
  "azernikov",
  "farran",
  "feuerstein",
  "brenneise",
  "ameduri",
  "labao",
  "dorfman",
  "norton"
 ],
 "layers": [
  {
   "z": 1850,
   "layer": "REC",
   "name": "glass hall — room plate (wall photograph, fitted to the wall height)",
   "x0": 35080,
   "x1": 36580
  },
  {
   "z": 1850,
   "layer": "FLOOR",
   "name": "glass hall — polished floor plate, under the whole late stretch",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 1400,
   "layer": "WALL",
   "name": "era 4 wall (wall4)",
   "x0": 25040,
   "x1": 44100
  },
  {
   "z": 1396,
   "layer": "LIGHT",
   "name": "era 4 lamp pool on the wall",
   "x0": 25040,
   "x1": 44100
  },
  {
   "z": 1394,
   "layer": "WALL",
   "name": "era 4 wall photographs",
   "x0": 25040,
   "x1": 44100
  },
  {
   "z": 1394,
   "layer": "REC",
   "name": "showroom ceiling soffit",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 1392,
   "layer": "REFLECT",
   "name": "floor sheen — fold at the wall foot",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 1392,
   "layer": "FLOOR",
   "name": "floor — back edge, at the foot of era 4's wall",
   "x0": 25040,
   "x1": 44100
  },
  {
   "z": 1000,
   "layer": "REC",
   "name": "2017 panel",
   "x0": 35130,
   "x1": 38610
  },
  {
   "z": 1000,
   "layer": "REC",
   "name": "2018 panel",
   "x0": 29270,
   "x1": 30170
  },
  {
   "z": 1000,
   "layer": "REC",
   "name": "2022 panel",
   "x0": 31960,
   "x1": 32760
  },
  {
   "z": 1000,
   "layer": "REC",
   "name": "2023 panel",
   "x0": 33470,
   "x1": 34370
  },
  {
   "z": 992,
   "layer": "REC",
   "name": "glass hall — doorway uprights (steel)",
   "x0": 35080,
   "x1": 36580
  },
  {
   "z": 970,
   "layer": "REC",
   "name": "Digital Revolution panel",
   "x0": 23960,
   "x1": 25040
  },
  {
   "z": 850,
   "layer": "WALL",
   "name": "era 3 wall (wall3)",
   "x0": 14720,
   "x1": 23960
  },
  {
   "z": 846,
   "layer": "LIGHT",
   "name": "era 3 lamp pool on the wall",
   "x0": 14720,
   "x1": 23960
  },
  {
   "z": 844,
   "layer": "WALL",
   "name": "era 3 wall photographs",
   "x0": 14720,
   "x1": 23960
  },
  {
   "z": 842,
   "layer": "FLOOR",
   "name": "floor — back edge, at the foot of era 3's wall",
   "x0": 14720,
   "x1": 23960
  },
  {
   "z": 728,
   "layer": "REC",
   "name": "1989 panel",
   "x0": 13620,
   "x1": 14720
  },
  {
   "z": 728,
   "layer": "REC",
   "name": "1993 panel",
   "x0": 15445,
   "x1": 16395
  },
  {
   "z": 680,
   "layer": "WALL",
   "name": "era 2 wall (wall2)",
   "x0": 10470,
   "x1": 13620
  },
  {
   "z": 680,
   "layer": "TYPE",
   "name": "era 2 year + title (on the wall)",
   "x0": 10470,
   "x1": 13620
  },
  {
   "z": 680,
   "layer": "TYPE",
   "name": "era 3 year + title (forward of the wall)",
   "x0": 14720,
   "x1": 23960
  },
  {
   "z": 680,
   "layer": "TYPE",
   "name": "era 4 year + title (forward of the wall)",
   "x0": 25040,
   "x1": 44100
  },
  {
   "z": 676,
   "layer": "LIGHT",
   "name": "era 2 lamp pool on the wall",
   "x0": 10470,
   "x1": 13620
  },
  {
   "z": 674,
   "layer": "WALL",
   "name": "era 2 wall photographs",
   "x0": 10470,
   "x1": 13620
  },
  {
   "z": 672,
   "layer": "FLOOR",
   "name": "floor — back edge, at the foot of era 2's wall",
   "x0": 10470,
   "x1": 13620
  },
  {
   "z": 640,
   "layer": "AIR",
   "name": "jet flyby at 1998 — left to right, once per visit",
   "x0": 16757,
   "x1": 20557
  },
  {
   "z": 640,
   "layer": "AIR",
   "name": "jet flyby at 2005 — right to left, once per visit",
   "x0": 20407,
   "x1": 24207
  },
  {
   "z": 610,
   "layer": "REC",
   "name": "1979 panel",
   "x0": 9370,
   "x1": 10470
  },
  {
   "z": 550,
   "layer": "WALL",
   "name": "era 1 wall (wall1)",
   "x0": -3450,
   "x1": 9370
  },
  {
   "z": 550,
   "layer": "TYPE",
   "name": "era 1 year + title (on the wall)",
   "x0": -3450,
   "x1": 9370
  },
  {
   "z": 546,
   "layer": "LIGHT",
   "name": "era 1 lamp pool on the wall",
   "x0": -3450,
   "x1": 9370
  },
  {
   "z": 544,
   "layer": "WALL",
   "name": "era 1 wall photographs",
   "x0": -3450,
   "x1": 9370
  },
  {
   "z": 542,
   "layer": "FLOOR",
   "name": "floor — back edge, at the foot of era 1's wall",
   "x0": -3450,
   "x1": 9370
  },
  {
   "z": 520,
   "layer": "LIGHT",
   "name": "showroom chandelier hoops",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 430,
   "layer": "PLINTH",
   "name": "1979 — the plant on its block, behind the eight",
   "x0": 9400,
   "x1": 10440
  },
  {
   "z": 420,
   "layer": "PLINTH",
   "name": "glass hall — the crown pedestal (an object in the room)",
   "x0": 35650,
   "x1": 36010
  },
  {
   "z": 340,
   "layer": "REFLECT",
   "name": "floor sheen — near edge (back of the counter)",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 340,
   "layer": "BENCH",
   "name": "counter — back edge",
   "x0": -3450,
   "x1": 41600
  },
  {
   "z": 300,
   "layer": "FLOOR",
   "name": "glass hall — red carpet, z 300 … 900",
   "x0": 35030,
   "x1": 36630
  },
  {
   "z": 240,
   "layer": "LIGHT",
   "name": "pendant lamps and bulbs",
   "x0": -3450,
   "x1": 41600
  },
  {
   "z": 240,
   "layer": "AIR",
   "name": "1993 aeroplane — in from the left at 1989, away at 1993 (PLANE93)",
   "x0": 14170,
   "x1": 15920
  },
  {
   "z": 232,
   "layer": "MACHINE",
   "name": "machining cell — the far one",
   "x0": 31140,
   "x1": 31140
  },
  {
   "z": 190,
   "layer": "MACHINE",
   "name": "machining cell — the near one",
   "x0": 30590,
   "x1": 30590
  },
  {
   "z": 120,
   "layer": "PLINTH",
   "name": "1973 — the two labs on their stones",
   "x0": 6670,
   "x1": 7430
  },
  {
   "z": 120,
   "layer": "PLINTH",
   "name": "1979 — eight labs on one plinth",
   "x0": 9220,
   "x1": 10620
  },
  {
   "z": 2,
   "layer": "GLOW",
   "name": "concealed strip + logo plates (era 4)",
   "x0": 36640,
   "x1": 41600
  },
  {
   "z": 0,
   "layer": "BENCH",
   "name": "counter — front edge",
   "x0": -3450,
   "x1": 41600
  },
  {
   "z": -40,
   "layer": "FLOOR",
   "name": "floor — front edge",
   "x0": -4350,
   "x1": 41600
  },
  {
   "z": -90,
   "layer": "PLINTH",
   "name": "pedestals (hero objects)",
   "x0": -3450,
   "x1": 41600
  }
 ]
};
