#!/usr/bin/env node
/* Regenerate the plan's data from the running hall.
   Opens expo.html?plan=1 in headless Chrome, waits until the hall has booted
   and published window.PLAN_DUMP, and writes expo/plan/plan-data.js. Run it
   after any change to bays, depths, breaks or pages; the plan sheets
   (expo/plan/index.html) redraw from the data on reload.

       node qa/plan_dump.mjs            # starts its own server on 8781
       node qa/plan_dump.mjs 8777       # use a server already running

   Chrome's --dump-dom exits at the load event, which is before the hall's
   async boot finishes — so this drives Chrome over its debugging protocol and
   polls for the object instead. */
import { spawn, execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port = process.argv[2] || '8781';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const alive = async () => { try { const r = await fetch(`http://localhost:${port}/expo/expo.html`, {method: 'HEAD'}); return r.ok; } catch { return false; } };

let server = null;
if (!(await alive())){
  server = spawn('python3', [join(ROOT, 'qa', 'serve.py'), port], {cwd: ROOT, stdio: 'ignore'});
  for (let i = 0; i < 40 && !(await alive()); i++) await sleep(250);
}
const profile = mkdtempSync(join(tmpdir(), 'plan-chrome-'));
const dbgPort = 9333 + Math.floor(Math.random() * 500);
const chrome = spawn(CHROME, ['--headless=new', '--disable-gpu', '--no-first-run', '--mute-audio',
  `--user-data-dir=${profile}`, '--window-size=1240,700', `--remote-debugging-port=${dbgPort}`, 'about:blank'], {stdio: 'ignore'});
const quit = code => { try { chrome.kill(); } catch {} if (server) server.kill(); process.exit(code); };
process.on('SIGINT', () => quit(130));

let target = null;
for (let i = 0; i < 60 && !target; i++){
  await sleep(250);
  try { const list = await (await fetch(`http://localhost:${dbgPort}/json`)).json(); target = list.find(t => t.type === 'page'); } catch {}
}
if (!target){ console.error('Chrome did not open a debugging target'); quit(1); }

const ws = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
let id = 0; const pending = new Map();
ws.onmessage = ev => { const m = JSON.parse(ev.data); if (m.id && pending.has(m.id)){ pending.get(m.id)(m); pending.delete(m.id); } };
const cdp = (method, params = {}) => new Promise(res => { const i = ++id; pending.set(i, res); ws.send(JSON.stringify({id: i, method, params})); });

await cdp('Page.enable');
await cdp('Page.navigate', {url: `http://localhost:${port}/expo/expo.html?plan=1&nc=${Date.now()}`});
let json = null;
for (let i = 0; i < 120 && !json; i++){          // up to 60 s for assets, fonts and the boot
  await sleep(500);
  const r = await cdp('Runtime.evaluate', {expression: 'window.PLAN_DUMP ? JSON.stringify(window.PLAN_DUMP) : null', returnByValue: true});
  if (r.result && r.result.result && typeof r.result.result.value === 'string') json = r.result.result.value;
}
if (!json){ console.error('the hall never published PLAN_DUMP — a boot error? open ?plan=1 in a browser and read the console'); quit(1); }
const plan = JSON.parse(json);
const dst = join(ROOT, 'expo', 'plan', 'plan-data.js');
writeFileSync(dst, '/* generated by qa/plan_dump.mjs from expo.html?plan=1 — do not edit by hand */\nwindow.PLAN = ' + JSON.stringify(plan, null, 1) + ';\n');
console.log(`wrote expo/plan/plan-data.js: ${plan.beats.length} beats, ${plan.breaks.length} breaks, ${plan.tables.length} tables, ${plan.layers.length} layers, date ${plan.date}`);
quit(0);
